Oy 4009
Opetushallitus/ataru pull request #1430
Opened 2023-05-29 06:58 UTC by janneslindberg

2023-05-29 07:35 UTC, marjakari commented on src/cljs/ataru/virkailija/application/application_review_view.cljs
> +              ;[information-request-view/information-request-link application-information-request-contains-modification-link]
Tarkoituksella tässä tämä kommentoitu pätkä?

2023-05-29 07:38 UTC, marjakari commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +    (println "suoritan 'confirm-single-information-request'")
jäänyt debug-tuloste?

2023-05-29 07:39 UTC, marjakari commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +      (println "Suoritan application/submit-single-information-request")
jäänyt debug-tuloste?

2023-05-29 07:39 UTC, marjakari commented on src/cljs/ataru/virkailija/application/mass_information_request/virkailija_mass_information_request_handlers.cljs
> +    (println "suoritan 'confirm-mass-information-request'")
jäänyt debug-tuloste?

2023-05-29 07:40 UTC, marjakari commented
Varmisteluna kysyn että oliko niin että tämän johdosta ei tullut mitään muutoksia käyttöoikeustarkistuksiin?

2023-05-29 09:53 UTC, SalamaGofore requested changes
Pari tyyliseikkaa ja melko paljon formatointiin liittyvää

2023-05-29 09:53 UTC, SalamaGofore commented on resources/less/virkailija-application.less
> +  left: -80px;
Ei näytä oikealta, mitä varten tämä on? Keskitystä? Sama ongelma toki tossa ylemmässä (ei sun muutoksessa)

2023-05-29 09:53 UTC, SalamaGofore commented on resources/less/virkailija-application.less
> +.application-handling__single-edit-review-states-title {
Tämä on identtinen ylemmän kanssa. Jos luokalle on silti tarvetta, niin:

.application-handling__mass-edit-review-states-title,
.application-handling__single-edit-review-states-title {

2023-05-29 09:53 UTC, SalamaGofore commented on resources/less/virkailija-application.less
> +.application-handling__send-message-button {
Tämä on melkein identtinen alla olevan link-buttonin kanssa.

Käytä samoja määrittelyjä molempiin ja anna send-message-buttonille erikseen tuo margin-bottom

2023-05-29 09:53 UTC, SalamaGofore commented on src/clj/ataru/information_request/information_request_service.clj
> +  (let [
formatointi: ylimääräinen rivinvaihto pois

2023-05-29 09:53 UTC, SalamaGofore commented on src/clj/ataru/information_request/information_request_service.clj
> +        ]
formatointi: ylimääräinen rivinvaihto pois

2023-05-29 09:53 UTC, SalamaGofore commented on src/clj/ataru/information_request/information_request_service.clj
> +    (let [
formatointi: ylimääräinen rivinvaihto pois

2023-05-29 09:53 UTC, SalamaGofore commented on src/clj/ataru/information_request/information_request_service.clj
> +        ]
formatointi: ylimääräinen rivinvaihto pois

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljc/ataru/translations/texts.cljc
> +   :single-applicant-email                                          {:fi "Viestin mukana lähetetään hakemuksen muokkauslinkki"
formatointi

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljc/ataru/translations/texts.cljc
> +   :single-information-request-send                            {:fi "Lähetä"
formatointi

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/application_review_view.cljs
> +            ))
formatointi, ylimääräiset rivinvaihdot pois tästä tiedostosta

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/application_subs.cljs
> +(re-frame/reg-sub
rivinvaihto tän ylle

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +     :dispatch-later [{:dispatch [:application/cancel-single-information-request]
Minkä takia tämä dispatch-later? Eikö email saata olla jo lähtenyt?

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +(reg-event-db
Puuttuva rivinvaihto

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +    (cond-> (assoc-in db [:application :single-information-request :message] message)
Tässä ei ehkä tarvittaisi condia? varmaan voisi asettaa suoraan enabloiduksi

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +(reg-event-fx
Puuttuva rivinvaihto

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +                                       )
Ylimääräinen rivinvaihto (dissoc :visible?))

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +(comment
Poista koko tämä blokki

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +                    [:application/fetch-application current-application])]
Tarviiko tätä tehdä? Muuttuuko hakemuksessa jotain?

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_view.cljs
> +  (let [
ylimääräinen rivinvaihto

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_view.cljs
> +            [:p @(subscribe [:editor/virkailija-translation :single-information-request-email-applicant (str last-name ", " first-name)])]
Täs taitaa sisennys mennä väärin

2023-05-29 09:53 UTC, SalamaGofore commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_view.cljs
> +             }]
Tyylillisesti ainakin atarun koodissa ei jätetä sulkevia (tahi avaavia) sulkuja yksin omille riveilleen

2023-05-29 13:05 UTC, janneslindberg commented on resources/less/virkailija-application.less
> +  left: -80px;
Ei varsinaisesti haettu keskitystä, yleisesti ottaen sivusuunnan sijoittelua. Ja top:lla ns. kiinni painikkeeseen.

2023-05-29 13:09 UTC, janneslindberg commented on resources/less/virkailija-application.less
> +.application-handling__single-edit-review-states-title {
Joo poistan, ei lopulta ollutkaan tarvetta omalle.

2023-05-29 13:55 UTC, janneslindberg commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +     :dispatch-later [{:dispatch [:application/cancel-single-information-request]
Tuo confirm-single-information-request oli kopio jostain massalähetyksen koodista, mutta sitä ei itse asiassa käytetä ollenkaan -> Poistan.

2023-05-30 07:21 UTC, janneslindberg commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +                    [:application/fetch-application current-application])]
Hakemuksen historiatietoihin tallennetaan se tapahtuma, että viesti on lähetetty ja haetaan ruudulle.

2023-06-07 11:55 UTC, janneslindberg commented on src/cljs/ataru/virkailija/application/application_review_view.cljs
> +              ;[information-request-view/information-request-link application-information-request-contains-modification-link]
Poistettu, oli jäänyt koodiin.

2023-06-07 11:55 UTC, janneslindberg commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +    (println "suoritan 'confirm-single-information-request'")
Poistettu, oli jäänyt koodiin.

2023-06-07 11:56 UTC, janneslindberg commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +      (println "Suoritan application/submit-single-information-request")
Poistettu, oli jäänyt koodiin.

2023-06-07 11:56 UTC, janneslindberg commented on src/cljs/ataru/virkailija/application/mass_information_request/virkailija_mass_information_request_handlers.cljs
> +    (println "suoritan 'confirm-mass-information-request'")
Poistettu, oli jäänyt koodiin.

2023-06-07 11:56 UTC, janneslindberg commented on resources/less/virkailija-application.less
> +  left: -80px;
Muokkasin nyt siten, että popupin oikea laita on tasattu painikkeiden oikean laidan kanssa.

2023-06-07 11:57 UTC, janneslindberg commented on resources/less/virkailija-application.less
> +.application-handling__send-message-button {
Muokattu.

2023-06-07 11:57 UTC, janneslindberg commented on src/clj/ataru/information_request/information_request_service.clj
> +  (let [
Korjattu.

2023-06-07 11:57 UTC, janneslindberg commented on src/clj/ataru/information_request/information_request_service.clj
> +        ]
Korjattu.

2023-06-07 11:57 UTC, janneslindberg commented on src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_handlers.cljs
> +(comment
Korjattu.

2023-06-12 08:44 UTC, SalamaGofore approved these changes

2023-07-06 07:02 UTC, merged