OY-4124 Use custom checkbox for hakija forms
Opetushallitus/ataru pull request #1445
Opened 2023-07-12 10:16 UTC by vaeinoe

2023-07-17 04:24 UTC, SalamaGofore requested changes

2023-07-17 04:24 UTC, SalamaGofore commented on resources/less/hakija.less
> +input.application__form-checkbox:checked {
Laita nämä sisäkkäin ylemmän määrittelyn kanssa käyttäen &:checked

Sama myös disabledille

2023-07-17 04:24 UTC, SalamaGofore commented on resources/less/hakija.less
> +label.application__form-checkbox.checked {
Laita nämä sisäkkäin ylemmän määrittelyn kanssa käyttäen .checked

Sama myös disabledille

2023-07-17 04:24 UTC, SalamaGofore commented on resources/less/hakija.less
> +  border-radius: 0.15em;
Näissä määrittelyissä voisi olla fiksumpaa käyttää remmiä, koska eihän me varmaan haluta et näistä olisi erilaisia kokoja samalla lomakkeella?

2023-07-17 07:18 UTC, vaeinoe commented on resources/less/hakija.less
> +  border-radius: 0.15em;
Hyvä pointti, muutin rem:iksi ja hienosäädin. Nuo checkboxit ovat nyt käytössä vain yhdessä lomakeosiossa (tai kahdessa jos koodistolla ja ilman -versiot lasketaan) eli em:ät ovat toistaiseksi aika turvallisia, mutta parempi varautua siihen että noita voidaan käyttää muuallakin.

2023-07-18 06:01 UTC, SalamaGofore approved these changes

2023-07-20 07:42 UTC, merged