Oy 4642 Näytetään uuden lomakkeen luonnissa ja latauksessa spinneri
Opetushallitus/ataru pull request #1502
Opened 2024-02-08 11:10 UTC by hajoa

2024-02-08 14:08 UTC, pretseli requested changes

2024-02-08 14:08 UTC, pretseli commented on playwright/tests/editori-lomake-yleiset.spec.ts
> +    // FIXME: Jos lomakkeen nimen syöttää liian aikaisin, automaattitallennus ei triggeröidy! https://jira.eduuni.fi/browse/OY-4642
Tämä kommentti viittaa tähän tikettiin. Hypoteesi oli, ettei tässä tarvitsisi enää odottaa jotain timeouttia, vaan voisi vain odottaa, että spinneri menee piiloon. Varmista, että näin on.

2024-02-12 11:24 UTC, hajoa commented on resources/less/editor.less
> +  .spin
ilman tota ei pyöri spinneri

2024-02-13 11:39 UTC, pretseli approved these changes

2024-02-15 15:31 UTC, merged