Oy 4656
Opetushallitus/ataru pull request #1503
Opened 2024-02-09 07:23 UTC by msiukola

2024-02-09 07:58 UTC, SalamaGofore requested changes

2024-02-09 07:58 UTC, SalamaGofore commented on src/cljs/ataru/hakija/application_handlers.cljs
> +      (js/console.log (str "Starting session polling, interval " polling-interval))
Logi

2024-02-09 07:58 UTC, SalamaGofore commented on src/cljs/ataru/hakija/application_handlers.cljs
> +    (js/console.log (str "Setting active warning for... " warning-minutes))
logi, btw, näissä myös toimisi prn

2024-02-09 07:58 UTC, SalamaGofore commented on src/cljs/ataru/hakija/application_handlers.cljs
> +          (js/console.log (str "Setting warning! " warning-to-set))
logi

2024-02-09 07:58 UTC, SalamaGofore commented on src/cljs/ataru/hakija/application_handlers.cljs
> +      (js/console.log (str "Maybe set warning? " warning-to-set ", previous" previous-warnings ", seconds left " seconds-left-in-session))
logi

2024-02-09 07:58 UTC, SalamaGofore commented on src/cljs/ataru/hakija/application_handlers.cljs
> +                                    (js/console.log (str "seconds left " seconds-left ", target-seconds" target-seconds
logi

2024-02-09 07:58 UTC, SalamaGofore commented on src/cljs/ataru/hakija/application_handlers.cljs
> +      (if warning-to-set
Tarviiko tässä if-elseä? Eikö pelkkä when riittäisi?

2024-02-09 07:58 UTC, SalamaGofore commented on src/cljs/ataru/hakija/application_handlers.cljs
> +  [check-schema-interceptor]
Eiks noista check-schema-interceptoreista pitänyt luopua?

2024-02-09 07:58 UTC, SalamaGofore commented on src/cljs/ataru/hakija/application_handlers.cljs
> +          should-set-warning-fn (fn [warning-target seconds-left]
Should kuulostaa vähän testikoodilta, voisiko olla toisen niminen esim.. get-warning-value-to-set-fn?

2024-02-09 07:58 UTC, SalamaGofore commented on src/cljs/ataru/hakija/application_handlers.cljs
> +      (js/console.log (str "Handle session login refresh, data " session-data))
Logi

2024-02-09 07:58 UTC, SalamaGofore commented on src/cljs/ataru/hakija/application_handlers.cljs
> +          should-set-warning-fn (fn [warning-target seconds-left]
Mietin myös et tän sisäfunkkarin voisi olla sopiva eriyttää ja tehdä sille yksikkötestit?

2024-02-12 08:56 UTC, msiukola commented on src/cljs/ataru/hakija/application_handlers.cljs
> +      (if warning-to-set
Eikö joku db pidä kuitenkin palauttaa tai se katoaa

2024-02-12 10:17 UTC, SalamaGofore approved these changes

2024-02-15 08:56 UTC, merged