OY-4565 Do lahtokoulu filtering based on cutoff date
Opetushallitus/ataru pull request #1526
Opened 2024-03-20 09:51 UTC by vaeinoe

Lähtökoulu data shown on the application view was based on most recent lähtökoulu and hence could change after application time was over. 

After this change, the visible lähtökoulu is the (most recent) one that was valid on the application end date.

There are no changes in the application access control in this PR - as it was a bit more complex than imagined, it was split to another ticket so we can do some planning beforehand.

2024-03-27 12:21 UTC, SalamaGofore requested changes
Hyvältä näytti mut renamee toi yksi parametri yhdenmukaiseksi

2024-03-27 12:21 UTC, SalamaGofore commented on src/clj/ataru/suoritus/suoritus_service.clj
> +  (opiskelija [_ henkilo-oid vuodet luokkatasot cutoff-timestamp]
cutoff-date vai cutoff-timestamp?

Yhdenmukaiset parametrin nimet mitä protokollassa

2024-04-02 07:09 UTC, vaeinoe commented on src/clj/ataru/suoritus/suoritus_service.clj
> +  (opiskelija [_ henkilo-oid vuodet luokkatasot cutoff-timestamp]
Oisko nyt? :)

2024-04-02 07:12 UTC, SalamaGofore approved these changes

2024-04-05 07:43 UTC, merged